apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: test-mc
  namespace: shoot--foobar--ionos
providerSpec:
  datacenterID: "7924c421-2495-43f3-8bd6-3afbafe1d6c8"
  cluster: "hugo"
  zone: "de/txl"
  cores: 1
  memory: 1024
  imageID: "57c979d6-f38a-11eb-9799-ca71ec1fa085"
  sshKey: "ssh-rsa invalid"
  networkID: "1"
secretRef: # If required
  name: ionos-test-secret
  namespace: shoot--foobar--ionos
