apiVersion: machine.sapcloud.io/v1alpha1
kind: Machine
metadata:
  name: test-machine
  namespace: shoot--foobar--ionos
spec:
  class:
    kind: MachineClass
    name: test-mc
    namespace: shoot--foobar--ionos
