name: go:pre-release

on:
  push:
    tags: 'v*'

jobs:
  create-pre-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        body: |-
          # [machine-controller-manager-provider-ionos] ${{ github.ref_name }}
        prerelease: true
  go-pre-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
    - name: Update VERSION file
      run: |-
          echo "${{ github.ref_name }}-rc.${{ github.sha }}" > VERSION
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/23technologies/machine-controller-manager-provider-ionos:${{ github.ref_name }}-rc.${{ github.sha }}
